### ISSUE TITLE
Add additional libraries to support Live Share

### ISSUE THREAD

**Issue by agilob** [flathub/com.visualstudio.code#35]
Live Share won't work until these libraries are available in the flatpak package 
https://docs.microsoft.com/en-us/visualstudio/liveshare/reference/linux#install-linux-prerequisites

**Comment by nedrichards** [comment]
Thanks, I'll look at making sure these dependencies are available - although some of the exports they document won't work.

**Comment by Plailect** [comment]
Has progress been made on this?

**Comment by Plailect** [comment]
So as it turns out everything actually works for this but the flatpak does not include xprop so the extension will complain on every launch. I fixed this by editing (and making executable) `~/.var/app/com.visualstudio.code/data/node_modules/bin/xprop` to:

```
#!/usr/bin/bash
flatpak-spawn --host xprop $@
```

**Comment by tinywrkb** [comment]
xprop didn't work for me before in the sandbox, but now it does, so it's possible to package it. Not sure what was changed in the runtime, libx11 and libxcb's build configs seems to be the same (default?).  

```
modules:
  - name: xprop
    sources:
      - type: archive
        url: https://xorg.freedesktop.org/archive/individual/app/xprop-1.2.4.tar.bz2
        sha256: 9b92ed0316bf2486121d8bac88bd1878f16b43bd335f18009b1f941f1eca93a1
        x-checker-data:
          type: anitya
          project-id: 14958
          url-template: https://xorg.freedesktop.org/archive/individual/app/xprop-$version.tar.bz2
```

Considering the previous issue, and the fact that I have no idea why it's magically working now, I'm not sending a PR.

**Comment by teohhanhui** [comment]
I think this issue can be closed, right? Since Live Share (even Live Share Audio) works perfectly.

The only thing that's not working is joining a Live Share session from the browser. There's no handler registered for `vsls:` links (even when I've tried manually registering it correctly, it still doesn't work because of the sandbox issue). Clicking on the `vscode:` link from the join page doesn't work either. But we should open another issue for this?

**Comment by yann-soubeyrand** [comment]
Hello, I still have the warning regarding missing xprop binary.
